### ISSUE TITLE
Just upgraded to Ubuntu 23.04, and BH crashes and burns.

### ISSUE THREAD

**Issue by ravenpi** [rcaloras/bashhub-client#122]
ken@mithrandir ~/tmp/switchportmapper $ bh
Traceback (most recent call last):
  File "/usr/lib/python3.11/importlib/metadata/__init__.py", line 563, in from_name
    return next(cls.discover(name=name))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
StopIteration

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ken/.bashhub/bin/bh", line 33, in <module>
    sys.exit(load_entry_point('bashhub===-version-', 'console_scripts', 'bh')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ken/.bashhub/bin/bh", line 22, in importlib_load_entry_point
    for entry_point in distribution(dist_name).entry_points
                       ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/importlib/metadata/__init__.py", line 981, in distribution
    return Distribution.from_name(distribution_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/importlib/metadata/__init__.py", line 565, in from_name
    raise PackageNotFoundError(name)
importlib.metadata.PackageNotFoundError: No package metadata was found for bashhub

**Comment by ravenpi** [comment]
@rcaloras 
Sorry, no dice, though a new error, now:
````
Pulling down bashhub-client from 2.4.0-dev branch
Pulling down a few dependencies...(this may take a moment)
          ____            _     _           _
         |  _ \          | |   | |         | |
         | |_) | __ _ ___| |__ | |__  _   _| |__   ___ ___  _ __ ___
         |  _ < / _` / __| '_ \| '_ \| | | | '_ \ / __/ _ \| '_ ` _  \
         | |_) | (_| \__ \ | | | | | | |_| | |_) | (_| (_) | | | | | |
         |____/ \__,_|___/_| |_|_| |_|\__,_|_.__(_)___\___/|_| |_| |_|

        
Welcome to bashhub setup!
Are you a new user? [Y/n] n
Please enter your bashhub credentials
Username: ravenpi
Password: 
400 Client Error: Bad Request for url: https://bashhub.com/api/v1/login
Please try again...
Please enter your bashhub credentials
Username: 
````

**Comment by ravenpi** [comment]
UPDATE: I can't re-authenticate during setup, apparently, but I just typed "bh" by accident, and guess what: it's working.

**Comment by rcaloras** [comment]
It likely preserved your config during install. Not sure why it failed to
authenticate though and can follow up.

**Comment by rcaloras** [comment]
@ravenpi Think I got it working in the latest dev branch. Mind giving a try?
`
curl -OL "https://bashhub.com/setup?version=2.4.1-dev" && bash setup 2.4.1-dev
`

**Comment by ravenpi** [comment]
@rcaloras 
I admit, I'm a little confused.  It seemed to work on my first host (running Ubuntu 23.04), but then I tried on my 23.04 ARM laptop, and no dice:

`ken@nano ~ $  curl -OL "https://bashhub.com/setup?version=2.4.1-dev" && bash setup 2.4.1-dev
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  8717  100  8717    0     0  32698      0 --:--:-- --:--:-- --:--:-- 32770
Using Python path /usr/bin/python3
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 10.7M  100 10.7M    0     0  10.1M      0  0:00:01  0:00:01 --:--:-- 16.5M
Pulling down bashhub-client from 2.4.1-dev branch
Pulling down a few dependencies...(this may take a moment)
          ____            _     _           _
         |  _ \          | |   | |         | |
         | |_) | __ _ ___| |__ | |__  _   _| |__   ___ ___  _ __ ___
         |  _ < / _` / __| '_ \| '_ \| | | | '_ \ / __/ _ \| '_ ` _  \
         | |_) | (_| \__ \ | | | | | | |_| | |_) | (_| (_) | | | | | |
         |____/ \__,_|___/_| |_|_| |_|\__,_|_.__(_)___\___/|_| |_| |_|

        
Welcome to bashhub setup!
Are you a new user? [Y/n] n
Please enter your bashhub credentials
Username: ravenpi
Password: 
{"code":401,"message":"incorrect Username or Password"}

Please enter your bashhub credentials
Username: ^C
`
