### ISSUE TITLE
bashhub installation failed.

### ISSUE THREAD

**Issue by cmal** [rcaloras/bashhub-client#44]
```
± |master ✓| → curl -OL https://bashhub.com/setup && bash setup
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  8377  100  8377    0     0    241      0  0:00:34  0:00:34 --:--:--  1825
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
 14 1957k   14  276k    0     0    184      0  3:01:34  0:25:38  2:35:56     0curl: (56) SSLRead() return error -36
virtualenv-1.9.1/virtualenv_support/distribute-0.6.34.tar.gz: (Empty error message)
tar: Error exit delayed from previous errors.
New python executable in env/bin/python2.7
Also creating executable in env/bin/python
Installing distribute.........
  Complete output from command /Users/cmal/.bashhub/env/bin/python2.7 -c "#!python
\"\"\"Bootstra...   sys.exit(main())
":
  Extracting in /var/folders/sf/83cds56n1gn45rw807f6twcr0000gn/T/tmp4Pcfam
Now working in /var/folders/sf/83cds56n1gn45rw807f6twcr0000gn/T/tmp4Pcfam/distribute-0.6.34
Installing Distribute
/Users/cmal/.bashhub/env/bin/python2.7: can't open file 'setup.py': [Errno 2] No such file or directory
Something went wrong during the installation.
See the error message above.
----------------------------------------
...Installing distribute...done.
Traceback (most recent call last):
  File "virtualenv-1.9.1/virtualenv.py", line 2577, in <module>
    main()
  File "virtualenv-1.9.1/virtualenv.py", line 979, in main
    no_pip=options.no_pip)
  File "virtualenv-1.9.1/virtualenv.py", line 1088, in create_environment
    search_dirs=search_dirs, never_download=never_download)
  File "virtualenv-1.9.1/virtualenv.py", line 616, in install_distribute
    search_dirs=search_dirs, never_download=never_download)
  File "virtualenv-1.9.1/virtualenv.py", line 583, in _install_req
    cwd=cwd)
  File "virtualenv-1.9.1/virtualenv.py", line 1057, in call_subprocess
    % (cmd_desc, proc.returncode))
OSError: Command /Users/cmal/.bashhub/env/bin/python2.7 -c "#!python
\"\"\"Bootstra...   sys.exit(main())
" failed with error code 2
setup: line 97: env/bin/pip: No such file or directory
x bashhub-client-1.1.4/
x bashhub-client-1.1.4/.gitignore
x bashhub-client-1.1.4/.travis.yml
x bashhub-client-1.1.4/LICENSE.md
x bashhub-client-1.1.4/MANIFEST.in
x bashhub-client-1.1.4/README.md
x bashhub-client-1.1.4/bashhub/
x bashhub-client-1.1.4/bashhub/__init__.py
x bashhub-client-1.1.4/bashhub/bashhub.py
x bashhub-client-1.1.4/bashhub/bashhub_globals.py
x bashhub-client-1.1.4/bashhub/bashhub_setup.py
x bashhub-client-1.1.4/bashhub/bh.py
x bashhub-client-1.1.4/bashhub/i_search.py
x bashhub-client-1.1.4/bashhub/interactive_search.py
x bashhub-client-1.1.4/bashhub/model/
x bashhub-client-1.1.4/bashhub/model/__init__.py
x bashhub-client-1.1.4/bashhub/model/command.py
x bashhub-client-1.1.4/bashhub/model/command_form.py
x bashhub-client-1.1.4/bashhub/model/min_command.py
x bashhub-client-1.1.4/bashhub/model/serializable.py
x bashhub-client-1.1.4/bashhub/model/status_view.py
x bashhub-client-1.1.4/bashhub/model/system.py
x bashhub-client-1.1.4/bashhub/rest_client.py
x bashhub-client-1.1.4/bashhub/shell/
x bashhub-client-1.1.4/bashhub/shell/bashhub.sh
x bashhub-client-1.1.4/bashhub/shell/bashhub.zsh
x bashhub-client-1.1.4/bashhub/shell/deps/
x bashhub-client-1.1.4/bashhub/shell/deps/bash-preexec.sh
x bashhub-client-1.1.4/bashhub/shell/deps/bashhub_completion_handler.sh
x bashhub-client-1.1.4/bashhub/shell/deps/lib-bashhub.sh
x bashhub-client-1.1.4/bashhub/shell_utils.py
x bashhub-client-1.1.4/bashhub/version.py
x bashhub-client-1.1.4/bashhub/view/
x bashhub-client-1.1.4/bashhub/view/__init__.py
x bashhub-client-1.1.4/bashhub/view/status.py
x bashhub-client-1.1.4/install-bashhub.sh
x bashhub-client-1.1.4/install_bashhub.py
x bashhub-client-1.1.4/setup.py
x bashhub-client-1.1.4/tests/
x bashhub-client-1.1.4/tests/__init__.py
x bashhub-client-1.1.4/tests/shell/
x bashhub-client-1.1.4/tests/shell/install-bashhub.bats
x bashhub-client-1.1.4/tests/shell/install-bashhub.fake-home.bats
x bashhub-client-1.1.4/tests/shell/lib-bashhub.bats
x bashhub-client-1.1.4/tests/test_bashhub.py
x bashhub-client-1.1.4/tests/test_bashhub_globals.py
x bashhub-client-1.1.4/tests/test_bashhub_setup.py
x bashhub-client-1.1.4/tests/test_command.py
x bashhub-client-1.1.4/tests/test_command_form.py
x bashhub-client-1.1.4/tests/test_shell_utils.py
x bashhub-client-1.1.4/uninstall-bashhub.sh
Pulling down a few dependencies...(this may take a moment)
setup: line 235: ../env/bin/pip: No such file or directory
setup: line 254: ../env/bin/bashhub: No such file or directory
chmod: /Users/cmal/.bashhub/config: No such file or directory
Please run 'bashhub setup' after restarting your terminal session.
```

**Comment by cmal** [comment]
and after restart my terminal...
```
 2017-03-25 11:18:39 ⌚  zhaoyutekiMacBook-Pro in ~
○ → bashhub setup
-bash: bashhub: command not found
```

**Comment by cmal** [comment]
Oh, I see.  The download is not completed.

**Comment by rcaloras** [comment]
Glad you were able to solve the issue. :+1:

**Comment by cmal** [comment]
```
± |master ?:1 ✗| → curl -OL https://bashhub.com/setup && bash setup
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  8377  100  8377    0     0   2981      0  0:00:02  0:00:02 --:--:--  2981

Looks like the bashhub client is already installed.

Lets go ahead and update it.

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 1957k  100 1957k    0     0   2257      0  0:14:48  0:14:47  0:00:01  1672
New python executable in env/bin/python2.7
Also creating executable in env/bin/python
Installing distribute...........................................................................................................................................................................................................................done.
Installing pip................done.
x bashhub-client-1.1.4/
x bashhub-client-1.1.4/.gitignore
x bashhub-client-1.1.4/.travis.yml
x bashhub-client-1.1.4/LICENSE.md
x bashhub-client-1.1.4/MANIFEST.in
x bashhub-client-1.1.4/README.md
x bashhub-client-1.1.4/bashhub/
x bashhub-client-1.1.4/bashhub/__init__.py
x bashhub-client-1.1.4/bashhub/bashhub.py
x bashhub-client-1.1.4/bashhub/bashhub_globals.py
x bashhub-client-1.1.4/bashhub/bashhub_setup.py
x bashhub-client-1.1.4/bashhub/bh.py
x bashhub-client-1.1.4/bashhub/i_search.py
x bashhub-client-1.1.4/bashhub/interactive_search.py
x bashhub-client-1.1.4/bashhub/model/
x bashhub-client-1.1.4/bashhub/model/__init__.py
x bashhub-client-1.1.4/bashhub/model/command.py
x bashhub-client-1.1.4/bashhub/model/command_form.py
x bashhub-client-1.1.4/bashhub/model/min_command.py
x bashhub-client-1.1.4/bashhub/model/serializable.py
x bashhub-client-1.1.4/bashhub/model/status_view.py
x bashhub-client-1.1.4/bashhub/model/system.py
x bashhub-client-1.1.4/bashhub/rest_client.py
x bashhub-client-1.1.4/bashhub/shell/
x bashhub-client-1.1.4/bashhub/shell/bashhub.sh
x bashhub-client-1.1.4/bashhub/shell/bashhub.zsh
x bashhub-client-1.1.4/bashhub/shell/deps/
x bashhub-client-1.1.4/bashhub/shell/deps/bash-preexec.sh
x bashhub-client-1.1.4/bashhub/shell/deps/bashhub_completion_handler.sh
x bashhub-client-1.1.4/bashhub/shell/deps/lib-bashhub.sh
x bashhub-client-1.1.4/bashhub/shell_utils.py
x bashhub-client-1.1.4/bashhub/version.py
x bashhub-client-1.1.4/bashhub/view/
x bashhub-client-1.1.4/bashhub/view/__init__.py
x bashhub-client-1.1.4/bashhub/view/status.py
x bashhub-client-1.1.4/install-bashhub.sh
x bashhub-client-1.1.4/install_bashhub.py
x bashhub-client-1.1.4/setup.py
x bashhub-client-1.1.4/tests/
x bashhub-client-1.1.4/tests/__init__.py
x bashhub-client-1.1.4/tests/shell/
x bashhub-client-1.1.4/tests/shell/install-bashhub.bats
x bashhub-client-1.1.4/tests/shell/install-bashhub.fake-home.bats
x bashhub-client-1.1.4/tests/shell/lib-bashhub.bats
x bashhub-client-1.1.4/tests/test_bashhub.py
x bashhub-client-1.1.4/tests/test_bashhub_globals.py
x bashhub-client-1.1.4/tests/test_bashhub_setup.py
x bashhub-client-1.1.4/tests/test_command.py
x bashhub-client-1.1.4/tests/test_command_form.py
x bashhub-client-1.1.4/tests/test_shell_utils.py
x bashhub-client-1.1.4/uninstall-bashhub.sh
Pulling down a few dependencies...(this may take a moment)
Exception:
Traceback (most recent call last):
  File "/Users/cmal/.bashhub/env/lib/python2.7/site-packages/pip-1.3.1-py2.7.egg/pip/basecommand.py", line 139, in main
    status = self.run(options, args)
  File "/Users/cmal/.bashhub/env/lib/python2.7/site-packages/pip-1.3.1-py2.7.egg/pip/commands/install.py", line 266, in run
    requirement_set.prepare_files(finder, force_root_egg_info=self.bundle, bundle=self.bundle)
  File "/Users/cmal/.bashhub/env/lib/python2.7/site-packages/pip-1.3.1-py2.7.egg/pip/req.py", line 1033, in prepare_files
    self.unpack_url(url, location, self.is_download)
  File "/Users/cmal/.bashhub/env/lib/python2.7/site-packages/pip-1.3.1-py2.7.egg/pip/req.py", line 1161, in unpack_url
    retval = unpack_http_url(link, location, self.download_cache, self.download_dir)
  File "/Users/cmal/.bashhub/env/lib/python2.7/site-packages/pip-1.3.1-py2.7.egg/pip/download.py", line 554, in unpack_http_url
    download_hash = _download_url(resp, link, temp_location)
  File "/Users/cmal/.bashhub/env/lib/python2.7/site-packages/pip-1.3.1-py2.7.egg/pip/download.py", line 458, in _download_url
    chunk = resp.read(4096)
  File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/socket.py", line 384, in read
    data = self._sock.recv(left)
  File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 612, in read
    s = self.fp.read(amt)
  File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/socket.py", line 384, in read
    data = self._sock.recv(left)
  File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ssl.py", line 734, in recv
    return self.read(buflen)
  File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ssl.py", line 621, in read
    v = self._sslobj.read(len or 1024)
SSLError: ('The read operation timed out',)

Storing complete log in /Users/cmal/.pip/pip.log
setup: line 254: ../env/bin/bashhub: No such file or directory
chmod: /Users/cmal/.bashhub/config: No such file or directory
Please run 'bashhub setup' after restarting your terminal session.
```

**Comment by cmal** [comment]
@rcaloras Can you help me with this? I don't know where is the problem. I've tried it for almost a whole day but I keeps getting this error.

**Comment by cmal** [comment]
Or can I download this package/dependencies first and then run setup, so the network will not be a problem?

**Comment by rcaloras** [comment]
@cmal Looks like the issue you're having is with `pip` pulling down the necessary dependencies. I'm not sure why it's error-ing, but it could be connectivity from the posts I'm seeing. Try editing the install script to have a very high default timeout as suggested here:
http://stackoverflow.com/a/19334551

Should be this line https://github.com/rcaloras/bashhub-client/blob/master/install-bashhub.sh#L235

```python
../env/bin/pip --default-timeout=100 install .
```
If that doesn't work I'd try to play with the pip params some more. Could be something funny going on with permissions.

**Comment by cmal** [comment]
Thanks a lot. I'll have a try.

**Comment by rcaloras** [comment]
@cmal closing this issue. Please reopen if you're still having any problems.
